def tip():
    print("       /\\    " * 2)
    print("      /  \\   " * 2)
    print("     /    \\  " * 2)
tip()
print('    +------+ ' * 2)
print('    |      | ' * 2)
print('    |      | ' * 2)
print('    +------+ ' * 2)
print('    |  TO  | ' * 2)
print('    |SPACE | ' * 2)
print('    +------+ ' * 2)
print('    |      | ' * 2)
print('    |      | ' * 2)
print('    +------+ ' * 2)
tip()
